Update Inference for multi-stage pipeline usecases
ADLINK-DEV/ADLINK-VisionDataModels-Reference pull request #9
Opened 2021-02-23 08:56 UTC by hendrenja

Kick-off Inference data-model update discussions. 

**Known Defects**
- `engine_id` shall be removed

**TODO**
- Explain use case requirements driving model changes

2021-02-23 12:25 UTC, geoffmartin-adlink requested changes
An additional comment that applies to all changes:

* New versions of tag groups should be added to an appropriately named file path. The 2.000 in the path needs to be changed to 2.001.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionBoxTagGroup.json
> +        "context":"com.adlinktech.vision",
Is there a reason for changing the context?

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionBoxTagGroup.json
> +        "version":"2.1.0",
Version should be 2.001.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionBoxTagGroup.json
> +                "name":"stream_id",
It was agreed that stream_id would be removed from the tag group and instead stream id would be encoded in the flow Id.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionBoxTagGroup.json
> +                "name":"model_id",
This is a problem for us as the results we are publishing from an inference pipeline are the combined results of the overall pipeline.

As I suggested previously by email could we make this a string sequence so that it can be a list of models that have acted to produce the results?

Also can be drop "unique" from the description. In absence of any other data we may just put the model filename here.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionBoxTagGroup.json
> +                "kind":"NVP_SEQ",
This needs to be MULTI_DIM_NVP with dimensions of 1.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionBoxTagGroup.json
> +                "name":"super_category_id",
What exactly is super_caregory used for?

I'd also suggest this should be optional.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionBoxTagGroup.json
> +                "name":"uuid",
I'm not sure what the purpose of this is from the description. Is this a UUID per inference result?

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionBoxTagGroup.json
> +                "name":"parent_id",
Relationships such as this should be represented as part of the flow Id rather than as a tag.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionBoxTagGroup.json
> +                "name":"physical_coords",
This needs to be optional.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionPointTagGroup.json
> +        "context":"com.adlinktech.vision",
Is there a reason for changing the context?

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionPointTagGroup.json
> +        "version":"2.1.0",
Version should be 2.001.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionPointTagGroup.json
> +                "name":"stream_id",
It was agreed that stream_id would be removed from the tag group and instead stream id would be encoded in the flow Id.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionPointTagGroup.json
> +                "kind":"NVP_SEQ",
This needs to be MULTI_DIM_NVP with dimensions of 1.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionPointTagGroup.json
> +                "name":"super_category_id",
What exactly is super_caregory used for?

I'd also suggest this should be optional.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionPointTagGroup.json
> -                "unit":"Hex Code #RRGGBB"
Ideally we should agree how we represent colour. Hex code seems reasonable?

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionPointTagGroup.json
> +                "name":"uuid",
I'm not sure what the purpose of this is from the description. Is this a UUID per inference result?

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionPointTagGroup.json
> +                "name":"parent_id",
Relationships such as this should be represented as part of the flow Id rather than as a tag.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/SegmentationTagGroup.json
> +        "context":"com.adlinktech.vision",
Is there a reason for changing the context?

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/SegmentationTagGroup.json
> +        "version":"2.1.0",
Version should be 2.001.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/SegmentationTagGroup.json
> +                "name":"stream_id",
It was agreed that stream_id would be removed from the tag group and instead stream id would be encoded in the flow Id.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/SegmentationTagGroup.json
> +                "kind":"NVP_SEQ",
This needs to be MULTI_DIM_NVP with dimensions.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/SegmentationTagGroup.json
>                  "name":"model_id",
We don't use segmentation yet but for consistency with the other tag groups ...

As I suggested previously by email could we make this a string sequence so that it can be a list of models that have acted to produce the results?

Also can be drop "unique" from the description. In absence of any other data we may just put the model filename here.

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/SegmentationTagGroup.json
> +                "name":"uuid",
I'm not sure what the purpose of this is from the description. Is this a UUID per inference result?

2021-02-23 12:25 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/SegmentationTagGroup.json
> +                "name":"parent_id",
Relationships such as this should be represented as part of the flow Id rather than as a tag.

2021-02-23 12:52 UTC, geoffmartin-adlink commented
Just spoken to Rob and on the subject of version numbers he's happy to switch to the style you've used @hendrenja . To be consistent with other usage in tag groups I'd suggest maybe going for v2.1.0?

Given the directory structure I'm wondering if we'd be better merging the changes onto a branch to keep the diffs clear then once the next version is agreed we can create the correct directory structure and merge to master?

2021-02-23 13:52 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/ClassificationTagGroup.json
> +                "name":"model_id",
See the PR I've raised to address our issues: https://github.com/ADLINK-DEV/ADLINK-VisionDataModels-Reference/pull/13

2021-02-23 14:50 UTC, geoffmartin-adlink commented
I've also suggested some changes on PR: https://github.com/ADLINK-DEV/ADLINK-VisionDataModels-Reference/pull/13 to accomodate our requirements.

2021-02-23 15:01 UTC, geoffmartin-adlink commented
Just to add a follow up on my comments on the parent_id tags added as part of this PR and how I think it should be part of the flow Id instead. This is based on a conversation I had with Hans regarding a similar but different use case we came across where we had two inference engines producing results for the same stream. We wanted to view both results in VMLink but we found the bounding boxes were flicking between the two result sets as VMLink were interpreting them as being one set of results.

His suggestion was that the two sets of results should be further scoped by flow Id to indicate that they were two different sets of inference results applying to the same stream. We didn't go down this route at that point as VMLink wasn't able to pick up such scoped flows.

I think a similar approach is needed here. Inference results could be published on scoped, hierarchical subflows to indicate the relationships.

I also suggested it may be beneficial to bring back the stream_id tag in such cases but Hans wasn't happy with that.

2021-02-25 11:46 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionBoxTagGroup.json
> +                "name":"parent_id",
Looking at this again I think I may possibly have misinterpreted the intention here as the uuid / parent_id is within each individual result.

Is the intention to be able to refer to a parent detection within the same result set? If so rather than Id could the sequence index not be used as an automatic ID?

2021-02-26 07:16 UTC, hendrenja commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/ClassificationTagGroup.json
> +        "context":"com.adlinktech.vision",
@geoffmartin-adlink - No, that should remain `"context":"com.adlinktech.vision.inference",`

2021-02-26 07:18 UTC, hendrenja commented
> * I spoke to Rob and he is okay with moving away from Ronald's x.yyy style to x.y.z style.

Sounds good!

> * New versions of tag groups should be added to an appropriately named file path. The updated tag groups need to go in a 2.1.0 folder. Given the directory structure change I'm wondering if we'd be better merging the changes onto a branch to keep the diffs clear then once the next version is agreed we can create the correct directory structure and merge to master?

We are on the same page. My plan was to open the pull request to review the changes and then move the changed files to a `2.1.0` directory.

2021-02-26 07:22 UTC, hendrenja commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/ClassificationTagGroup.json
> +                "name":"stream_id",
@geoffmartin-adlink, I thought we agreed to remove `engine_id` while keeping `stream_id` as an inference engine can process multiple streams. 

Our codebase was not ready to remove `engine_id` prior to the data models update. `engine_id` should be removed from `2.1.0`.

2021-02-26 07:33 UTC, hendrenja commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/ClassificationTagGroup.json
> +                "name":"model_id",
@geoffmartin-adlink - The `model_id` can be the model architecture like `AlexNet` (Classification Net), `ECC200` (barcode reader), or a UUID for a VMLINK model. 

I'm good with this being s `STRING_SEQ`

2021-02-26 07:37 UTC, hendrenja commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/ClassificationTagGroup.json
> +                "description":"Unique inference identifier",
This is a unique instance of an inference result. We ran into issues where we needed to know that we had received an updated sample for a tracked object. The following example likely paints a better picture:

- Sample 1 (**Obj Tracker ID**: `123`, **UUID**: `ABCD-xxx-123``)
- Sample 2 (**Obj Tracker ID**: `122`, **UUID**: `AKDC-xxx-453``)
- Sample 3 (**Obj Tracker ID**: `124`, **UUID**: `KDND-xxx-382``)
- Sample 4 (**Obj Tracker ID**: `123`, **UUID**: `QKDCxxx-149``)

2021-02-26 07:39 UTC, hendrenja commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/SegmentationTagGroup.json
> +                "name":"stream_id",
@hansvanthag & @geoffmartin-adlink - How would `stream_id` be encoded within the flow ID? 

My understanding was that we would remove `engine_id` but we would keep `stream_id` as engines process multiple streams.

2021-02-26 07:39 UTC, hendrenja commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/SegmentationTagGroup.json
> +                "kind":"NVP_SEQ",
@geoffmartin-adlink  - Thank you - this was another reverted hack to buy some time in our protobuf (de)serializer

2021-02-26 07:40 UTC, hendrenja commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/SegmentationTagGroup.json
>                  "name":"model_id",
@geoffmartin-adlink Sounds good!

2021-02-26 07:41 UTC, hendrenja commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/SegmentationTagGroup.json
> +                "name":"uuid",
Yes, same as [Classification::uuid[(https://github.com/ADLINK-DEV/ADLINK-VisionDataModels-Reference/pull/9#discussion_r583438380)

2021-02-26 07:45 UTC, hendrenja commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/SegmentationTagGroup.json
> +                "name":"parent_id",
@geoffmartin-adlink, Using the flow ID for this will be very difficult. We use `parent_id` to refer to an inference result in an upstream pipeline stage. Example:

**Stage 1 Detection**
- Bounding Box 1 UUID: `ABCDEFG` 
- Bounding Box 2 UUID: `LMNOPQ`

**Stage 2 Classification**
- Classification 1 `parent_id`: `ABCDEFG` 
- Classification 1 `parent_id`: `LMNOPQ`

2021-02-26 07:50 UTC, hendrenja commented
@geoffmartin-adlink Re:`parent_id`
> Just to add a follow up on my comments on the parent_id tags added as part of this PR and how I think it should be part of the flow Id instead. This is based on a conversation I had with Hans regarding a similar but different use case we came across where we had two inference engines producing results for the same stream. We wanted to view both results in VMLink but we found the bounding boxes were flicking between the two result sets as VMLink were interpreting them as being one set of results.
> His suggestion was that the two sets of results should be further scoped by flow Id to indicate that they were two different sets of inference results applying to the same stream. We didn't go down this route at that point as VMLink wasn't able to pick up such scoped flows.

That flicker issue was resolved a while ago in the latest VMLINK. VMLINK now uses the `producer_id` and `flow_id` to support painting inference results from inference engines. 

> I also suggested it may be beneficial to bring back the stream_id tag in such cases but Hans wasn't happy with that.
@hansvanthag hates `stream_id` lol!! 

We are at a good point now to set up a call to review your "merged" merge request.

2021-02-26 08:46 UTC, hansvanthag commented
HaHa.. I don't hate streamId, I just 'value' the difference between an 'element' and a 'key' in structured data (-flows) :)

The dataRiver (as the name says) is clearly about 'flows of data' (as flowId says) and for easy selection/consumption/digestion of such data-flows it really makes sense to be aware of their identity/context/lifecycle (as captured in the flowId).

Of course you could do without structure/keys/lifecycle etc. (as you would have to do when exploiting 'plumbing' like MQTT rather than structured-data-sharing that DDS provides), in which case its just the 'content/elements' of the data-blob that needs to be properly interpreted, as is the case when using a 'streamId' as (just) and attribute of the data .. 

Conversely if you DO want to take benefits of proper flow-identification (as 'keys' in DDS), processing(including filtering and querying) and management (esp. the lifecycle-management and awareness of new/stale flows), your design has to indeed exploit it (and will become different yet simpler as without using flowId's).

So i.m.o. it would be beneficial to exploit flowId's as streamId's (as both names suggested they are about the same thing) and exploit the added-value of hierarchical-composition, filtering with optional wildcards, querying within the business-logic as it could potentially reduce a lot of the complexity in the business-logic.

Of course, as was so often the case, if your business-logic is already 'carved-in-stone' (which is basically equal to saying 'yeah yeah we'll do it in a future update .. which never comes :) ) .. it doesn't make a lot of difference (besides maybe reducing flickering which is a consequence of sharing the same input-queue (reader-history) between 'flows' (of equal flowId) yet different 'streamid's' within the data.

2021-02-26 12:08 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/ClassificationTagGroup.json
> +                "name":"stream_id",
It sounds like there has been some confusion here in that case. From our side we all believed this to be the case, Ronald added descriptions to some of the tag groups to indicate this (I've corrected this inconsistency in my "merged" PR) and there are discussions on Confluence around removing it although I think you've had access issues with that.

Referring to what Hans was saying about the data river being about flows of data I think what's key in this case is that the result applies to a particular stream and so that should be reflected in the flow Id.

As you mentioned engines simply process one or more streams of data and the relationship to the data here is that the result was produced by this inference engine operating on that stream. As such I think engine_id is a useful (optional?) value to know. 

That being said I think there may be a place for both stream id and engine id in the flow Id. Going back to the issue we had when two separate inference engines were producing inference results for the same stream on the same flow Id. Beyond the issue with VMLink flickering there was also an issue that we were publishing two different sets of data to the same instance on the data river. Really these two inference streams should have been further scoped using flow Id to ensure each mapped to a unique instance on the data river. As our version of VMLink didn't support this we worked around the issue but I would propose the following pattern for the flow Id that inference results are published on:

<stream id>.<engine id> (where engine id uniquely identifies the producer of the data.

2021-02-26 12:18 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/ClassificationTagGroup.json
> +                "description":"Unique inference identifier",
I didn't consider that this may be for tracked objects. Doesn't the telemetry QoS profile already take care of this requirement though as you should be able to rely on the fact that the last sample read for a particular tracked object is the latest?

Is this also the id that is referred to by parent_id?

2021-02-26 12:36 UTC, geoffmartin-adlink commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/SegmentationTagGroup.json
> +                "name":"parent_id",
After further thought (and realising this applied to a result within the data list) I can see how using flow Id would be difficult in this case.

We handle results like these differently by publishing a DetectionBox result with additional labels generated by secondary classification models (or a Classification result which is the combination of several classification type models). This is in part due to the way DeepStream and Deep Learning Streamer work. We get a combined result after it has been fed through the inference pipeline.

I think both representations are valid and if @hansvanthag has no objections I'm happy to add both uuid and parent_id tags to all relevant tag groups.

2021-02-26 12:44 UTC, geoffmartin-adlink commented
@hendrenja in my "merged" PR I've set the version to 2.2.0 with my thinking being you may have already deployed tag groups with version 2.1.0 in them so skipping a version may ensure no clashes.

We're still working on migrating all of our apps to the new tag groups and will be continuing to do so throughout March. I'm happy for us to work towards implementing a 2.2.0 version of the tag groups once agreed leaving 2.1.0 for you to cover any of your existing uses of the groups. You could then catch up as time allows. Does this work for you?

2021-02-26 12:54 UTC, geoffmartin-adlink commented
@hansvanthag and I have already discussed how the intention with the current version of the tag groups was to bring the UK team and @hendrenja  team back in sync rather than to fundamentally change the model. Unfortunately I agree with your assesment Hans that its often difficult to get the time to "do it in a future update".

So far in the UK we're mainly concerned with the inference result tag groups. For (relatively) raw inference results from an engine I think the tag groups as they are are okay. These results tend to be be transient and relating them to a stream with telemetry QoS is okay.

One area we could potentially improve on in future is how we represent tracked objects. These objects, unlike untracked objects, have a lifecycle. The come in to existance when they are detected, their state is updated as further observations are made and when they are no longer visiable they cease to exist in the system. This could all be modelled in the data river using flow Ids and flow states.

Another area that could potentially be enhanced is in how we represent components of the system such as cameras, inference engines etc.

Such discussions are beyond the scope of this PR however :-)

2021-02-26 12:58 UTC, geoffmartin-adlink commented
@hendrenja one more question. I asked what the purpose of super_category_id/label was? I can see a use for this (e.g. storing the result of a primary object detection model in this field) but wanted to check what the exact intention was so we know how to use it correctly.

2021-02-26 13:23 UTC, hansvanthag commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/ClassificationTagGroup.json
> +                "name":"stream_id",
Yep, such use would provide all necessary 'context' to properly 'digest' a/each flow. Noting also that you could both filter and/or query on either inferenceing-results from a particular stream (as produced by potentially multiple IE's) and/or results from a particular inferencing engine (as produced by a particular IE, if that would make sense of course).

2021-02-26 13:27 UTC, hansvanthag commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/SegmentationTagGroup.json
> +                "name":"stream_id",
especially if 1 source would produce multiple streams (i.e. 'flows') it makes sense to capture those streams as (part of) the flowId.

As Geoff elsewhere suggested, the advantage of using flowId is that it offers capabilities to filter/query which is NOT possible with 'simple' attributes. 

Another example of benefitting from flows (with their lifecycle) is the bundled S4 example where multiple camera's observe pallets/boxes where (updates of) an observed barcode is considered a flow (related to 'that' barcode) ... but thats perhaps more a usecase of (future) 'object-tracking'

2021-03-01 08:23 UTC, hansvanthag commented on definitions/TagGroup/com.adlinktech.vision.inference/2.000/SegmentationTagGroup.json
> +                "name":"parent_id",
Yeah I'd have to agree that capturing such kind of references (i.e. to upstream 'internal' pipeline-stages) leans towards how to 'proper digest' the data-flow rather than how to properly capture the context of 'this' flow (i.e. what it is about) as captured by its flowId

2021-03-01 14:49 UTC, hendrenja commented
@hansvanthag I agree with you that it `stream_id` in `flowID` would offer the benefits you pointed out. My struggle has been how to differentiate `stream_id` and `engine_id` in a `flowID`? I feel like we would have to overlay a schema on the `flowId` and that _feels_ wrong. 

How do you handle/support the following valid `flowID`?
- **App A Flow ID:** `context.id.adlink.<stream_id>.<engine_ud>`
- **Customer App B Flow ID:** `context.id.<customer>.<engine_id>.<stream_id>`

2021-03-01 14:57 UTC, hendrenja commented
@geoffmartin-adlink **Re: super_category_id & super_category_label**

These were added to more closely align us with the [COCO standard format _(See Categories)_](https://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch/#coco-dataset-format). Example Object Detection Result:
```json
"categories": [
    {"supercategory": "person","id": 1,"name": "person"},
    {"supercategory": "vehicle","id": 2,"name": "bicycle"},
    {"supercategory": "vehicle","id": 3,"name": "car"},
    {"supercategory": "vehicle","id": 4,"name": "motorcycle"},
    {"supercategory": "vehicle","id": 5,"name": "airplane"},
    ...
    {"supercategory": "indoor","id": 89,"name": "hair drier"},
    {"supercategory": "indoor","id": 90,"name": "toothbrush"}
]
```

`super_category_id` was added to track the ID of the super-category. This was needed to support detection networks with embedded classification. It is similar to mapping a `DetectionBox` result to a `Classification` result using `DetectionBox::uuid` and `Classification::parent_id`.

2021-03-22 10:52 UTC, geoffmartin-adlink commented
Incorporated into PR #16.

2021-03-22 10:52 UTC, closed without merging